version: '3'
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: bookworm_nginx
    ports:
      - '80:80'
    volumes:
      - './:/app'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - app
      - pgsql

  pgsql:
    image: 'postgres:13-alpine'
    container_name: bookworm_postgres
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'bookworm_pgsql:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]

  app:
    build: .
    container_name: bookworm_app
    user: '${UID:-1000}:${GID:-1000}'
    volumes:
      - './:/app'
    depends_on:
      - pgsql

  adminer:
    image: dockette/adminer:pgsql
    container_name: bookworm_adminer
    ports:
      - '81:80'

volumes:
    bookworm_pgsql:
